version: '3'
services:
  auth-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_USER: keystore 
      DB_PASS: Ad4hjZOohoM74iIG 
      SECRET: JSJDAAMFKJAUFMCKOPOAKCIKJOA@%&$JNASJNDsdaasfasfc$%$@